from enum import StrEnum


class AccountStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    LOCKED = "LOCKED"
    INACTIVE = "INACTIVE"


class UserRole(StrEnum):
    USER = "USER"
    MEMBER = "MEMBER"
    COURIER = "COURIER"
    ADMIN = "ADMIN"


class MembershipStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class CourierStatus(StrEnum):
    PENDING = "PENDING"
    AVAILABLE = "AVAILABLE"
    BUSY = "BUSY"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class AdminStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    INACTIVE = "INACTIVE"


class BookCondition(StrEnum):
    NEW = "NEW"
    GOOD = "GOOD"
    FAIR = "FAIR"
    WORN = "WORN"


class ExchangeMode(StrEnum):
    PERMANENT_EXCHANGE = "PERMANENT_EXCHANGE"
    BORROW_RETURN = "BORROW_RETURN"
    BOTH = "BOTH"


class BookStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    PENDING_TRANSACTION = "PENDING_TRANSACTION"
    BORROWED = "BORROWED"
    EXCHANGED = "EXCHANGED"
    REMOVED = "REMOVED"


class TransactionType(StrEnum):
    PERMANENT_EXCHANGE = "PERMANENT_EXCHANGE"
    BORROW_RETURN = "BORROW_RETURN"


class DeliveryMethod(StrEnum):
    DIRECT_CONTACT = "DIRECT_CONTACT"
    FREE_COURIER = "FREE_COURIER"


class TransactionStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    DELIVERING = "DELIVERING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    PICKED_UP = "PICKED_UP"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RoleInTransaction(StrEnum):
    OWNER = "OWNER"
    REQUESTER = "REQUESTER"
    COURIER = "COURIER"
    SYSTEM = "SYSTEM"
    ADMIN = "ADMIN"


class PointLedgerReason(StrEnum):
    INITIAL_BONUS = "INITIAL_BONUS"
    EXCHANGE_REWARD = "EXCHANGE_REWARD"
    EXCHANGE_COST = "EXCHANGE_COST"
    BORROW_REWARD = "BORROW_REWARD"
    BORROW_COST = "BORROW_COST"
    DELIVERY_REWARD = "DELIVERY_REWARD"
    ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT"


class ReviewType(StrEnum):
    OWNER_REVIEW = "OWNER_REVIEW"
    REQUESTER_REVIEW = "REQUESTER_REVIEW"
    COURIER_REVIEW = "COURIER_REVIEW"


class ActivityType(StrEnum):
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    UPDATE_PROFILE = "UPDATE_PROFILE"
    CREATE_BOOK = "CREATE_BOOK"
    UPDATE_BOOK = "UPDATE_BOOK"
    CREATE_TRANSACTION = "CREATE_TRANSACTION"
    CONFIRM_TRANSACTION = "CONFIRM_TRANSACTION"
    DELIVERY_UPDATE = "DELIVERY_UPDATE"
    CREATE_REVIEW = "CREATE_REVIEW"
    POINT_UPDATE = "POINT_UPDATE"


class AdminActionType(StrEnum):
    LOCK_USER = "LOCK_USER"
    UNLOCK_USER = "UNLOCK_USER"
    HIDE_BOOK = "HIDE_BOOK"
    RESTORE_BOOK = "RESTORE_BOOK"
    CANCEL_TRANSACTION = "CANCEL_TRANSACTION"
    HIDE_REVIEW = "HIDE_REVIEW"
    POINT_ADJUSTMENT = "POINT_ADJUSTMENT"
    OTHER = "OTHER"
